### ISSUE TITLE
Uninstall option for install script

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-terminator#3]
Implement a `uninstall` option to allow users to remove the local installed color theme file again including a optional name parameter for custom named theme files.
The user should be asked to confirm this process before removing the file.

**Comment by tong** [comment]
Wiping existing config without confirmation and warning is pretty rude and not what i expected.
This should at least be clearly visible in README.
A merge into existing config would be preferable.

**Comment by privorotskii** [comment]
Any updates here? I just tried to run install.sh and get all my local settings wiped and I had to restore all of them manually. It is really unexpected and frustrating behaviour.

**Comment by tong** [comment]
This should be fixed!

**Comment by arcticicestudio** [comment]
@TolichP Thanks a lot for the report 🙏 
I'm really sorry for the data loss and hope you were able to restore the config again.

I've never really like these scripts so I've documented the bug in #12 and fixed it in #13.
This will now also make this issue as well as #4 obsolete.
